/* some objects for initial page */

var obj1 = {
	Actors: "Jason Statham, Josh Hartnett, Jeffrey Donovan, Niamh Algar",
	Awards: "N/A",
	BoxOffice: "N/A",
	Country: "UK, USA",
	DVD: "N/A",
	Director: "Guy Ritchie",
	Genre: "Action, Thriller",
	Language: "English",
	Metascore: "N/A",
	Plot: "The plot follows H, a cold and mysterious character working at a cash truck company responsible for moving hundreds of millions of dollars around Los Angeles each week.",
	Poster: "https://m.media-amazon.com/images/M/MV5BNGVkOTlhOTktNjZiNS00NDg3LWIxMDAtZTY5Y2E0YjllN2IxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
	Production: "Flic Films UK, Miramax, CAA Media Finance, MGM, Toff Guy Films",
	Rated: "R",
	Ratings: [{}, {
		Source: "Rotten Tomatoes",
		Value: "70%"
	}],
	Released: "07 May 2021",
	Response: "True",
	Runtime: "118 min",
	Title: "Wrath of Man",
	Type: "movie",
	Website: "N/A",
	Writer: "Guy Ritchie (screenplay by), Ivan Atkinson (screenplay by), Marn Davies (screenplay by), Éric Besnard (motion picture \"Le Convoyeur\"), Nicolas Boukhrief (motion picture \"Le Convoyeur\")",
	Year: "2021",
	imdbID: "tt11083552",
	imdbRating: "N/A",
	imdbVotes: "N/A",
};

var obj2 = {
	Actors: "Lewis Tan, Jessica McNamee, Josh Lawson, Joe Taslim",
	Awards: "1 nomination.",
	BoxOffice: "N/A",
	Country: "Australia, USA",
	DVD: "23 Apr 2021",
	Director: "Simon McQuoid",
	Genre: "Action, Adventure, Fantasy, Sci-Fi, Thriller",
	Language: "English",
	Metascore: "N/A",
	Plot: "MMA fighter Cole Young seeks out Earth's greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.",
	Poster: "https://m.media-amazon.com/images/M/MV5BY2ZlNWIxODMtN2YwZi00ZjNmLWIyN2UtZTFkYmZkNDQyNTAyXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_SX300.jpg",
	Production: "Broken Road Productions, New Line Cinema, Atomic Monster, Warner Bros., NetherRealm Studios",
	Rated: "R",
	Ratings: [
		{Source: "Internet Movie Database", Value: "7.1/10"}, 
		{Source: "Rotten Tomatoes", Value: "55%"}
	],
	Released: "23 Apr 2021",
	Response: "True",
	Runtime: "110 min",
	Title: "Mortal Kombat",
	Type: "movie",
	Website: "N/A",
	Writer: "Greg Russo (screenplay by), Dave Callaham (screenplay by), Oren Uziel (story by), Greg Russo (story by), Ed Boon (based on the videogame created by), John Tobias (based on the videogame created by)",
	Year: "2021",
	imdbID: "tt0293429",
	imdbRating: "7.1",
	imdbVotes: "2,996"
};

var obj3 = {
	Actors: "Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall, Brian Tyree Henry",
	Awards: "N/A",
	BoxOffice: "$83,375,844",
	Country: "USA, Australia, Canada, India",
	DVD: "31 Mar 2021",
	Director: "Adam Wingard",
	Genre: "Action, Sci-Fi, Thriller",
	Language: "English, American Sign Language",
	Metascore: "59",
	Plot: "The epic next chapter in the cinematic Monsterverse pits two of the greatest icons in motion picture history against one another - the fearsome Godzilla and the mighty Kong - with humanity caught in the balance.",
	Poster: "https://m.media-amazon.com/images/M/MV5BZmYzMzU4NjctNDI0Mi00MGExLWI3ZDQtYzQzYThmYzc2ZmNjXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
	Production: "Warner Bros., Legendary Entertainment",
	Rated: "PG-13",
	Ratings: [
		{Source: "Internet Movie Database", Value: "6.5/10"},
		{Source: "Rotten Tomatoes", Value: "75%"},
		{Source: "Metacritic", Value: "59/100"}
	],
	Released: "31 Mar 2021",
	Response: "True",
	Runtime: "113 min",
	Title: "Godzilla vs. Kong",
	Type: "movie",
	Website: "N/A",
	Writer: "Terry Rossio (story by), Michael Dougherty (story by), Zach Shields (story by), Eric Pearson (screenplay by), Max Borenstein (screenplay by)",
	Year: "2021",
	imdbID: "tt5034838",
	imdbRating: "6.5",
	imdbVotes: "105,096"
};

var obj4 = {
	Actors: "Bob Odenkirk, Aleksey Serebryakov, Connie Nielsen, Christopher Lloyd",
	Awards: "N/A",
	BoxOffice: "$19,811,720",
	Country: "USA",
	DVD: "15 Apr 2021",
	Director: "Ilya Naishuller",
	Genre: "Action, Crime, Drama, Thriller",
	Language: "Spanish, Russian, English",
	Metascore: "63",
	Plot: "A bystander who intervenes to help a woman being harassed by a group of men becomes the target of a vengeful drug lord.",
	Poster: "https://m.media-amazon.com/images/M/MV5BMjM5YTRlZmUtZGVmYi00ZjE2LWIyNzAtOWVhMDk1MDdkYzhjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg",
	Production: "87North, Odenkirk Provissiero Entertainment, Eighty Two Films",
	Rated: "R",
	Ratings: [
		{Source: "Internet Movie Database", Value: "7.5/10"},
		{Source: "Rotten Tomatoes", Value: "82%"},
		{Source: "Metacritic", Value: "63/100"}
	],
	Released: "26 Mar 2021",
	Response: "True",
	Runtime: "92 min",
	Title: "Nobody",
	Type: "movie",
	Website: "N/A",
	Writer: "Derek Kolstad",
	Year: "2021",
	imdbID: "tt7888964",
	imdbRating: "7.5",
	imdbVotes: "41,780"
};

var obj5 = {
	Actors: "Tom Hiddleston, Sophia Di Martino, Richard E. Grant, Gugu Mbatha-Raw",
	Awards: "N/A",
	Country: "USA",
	Director: "N/A",
	Genre: "Action, Adventure, Fantasy, Sci-Fi",
	Language: "English",
	Metascore: "N/A",
	Plot: "A new Marvel chapter with Loki at its center.",
	Poster: "https://m.media-amazon.com/images/M/MV5BOGU0OWQyMjItYzA4Zi00MDFiLThiZWQtZmEyNWRiODAzYzNmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
	Rated: "PG-13",
	Ratings: [],
	Released: "11 Jun 2021",
	Response: "True",
	Runtime: "29 min",
	Title: "Loki",
	Type: "series",
	Writer: "N/A",
	Year: "2021–",
	imdbID: "tt9140554",
	imdbRating: "N/A",
	imdbVotes: "N/A",
	totalSeasons: "1",
};

var obj6 = {
	Actors: "Ryan Reynolds, Frank Grillo, Salma Hayek, Samuel L. Jackson",
	Awards: "N/A",
	BoxOffice: "N/A",
	Country: "USA, UK",
	DVD: "N/A",
	Director: "Patrick Hughes",
	Genre: "Action, Comedy, Crime, Thriller",
	Language: "English",
	Metascore: "N/A",
	Plot: "The bodyguard Michael Bryce continues his friendship with assassin Darius Kincaid as they try to save Darius's wife Sonia.",
	Poster: "https://m.media-amazon.com/images/M/MV5BNDkzYmNiOWYtNzZkNi00NzNiLTk2MzktY2VmMGY4MmI1NDMwXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg",
	Production: "N/A",
	Rated: "R",
	Ratings: [],
	Released: "16 Jun 2021",
	Response: "True",
	Runtime: "142 min",
	Title: "The Hitman's Wife's Bodyguard",
	Type: "movie",
	Website: "N/A",
	Writer: "Tom O'Connor (screenplay), Brandon Murphy (screenplay), Tom O'Connor (based on characters created by), Tom O'Connor (story), Phillip Murphy (screenplay)",
	Year: "2021",
	imdbID: "tt8385148",
	imdbRating: "N/A",
	imdbVotes: "N/A",
};

var obj7 = {
	Actors: "Tom Hardy, Michelle Williams, Woody Harrelson, Stephen Graham",
	Awards: "N/A",
	BoxOffice: "N/A",
	Country: "USA",
	DVD: "N/A",
	Director: "Andy Serkis",
	Genre: "Action, Horror, Sci-Fi, Thriller",
	Language: "English",
	Metascore: "N/A",
	Plot: "Plot unknown. Sequel to the 2018 film 'Venom'.",
	Poster: "https://m.media-amazon.com/images/M/MV5BZjVmYzVjZWUtODE3NS00ZTExLThhMTUtNzU3ZGE2NGYwOWE4XkEyXkFqcGdeQXVyMTAwODc1OTcy._V1_SX300.jpg",
	Production: "N/A",
	Rated: "R",
	Ratings: [],
	Released: "24 Sep 2021",
	Response: "True",
	Runtime: "135 min",
	Title: "Venom: Let There Be Carnage",
	Type: "movie",
	Website: "N/A",
	Writer: "Kelly Marcel",
	Year: "2021",
	imdbID: "tt7097896",
	imdbRating: "N/A",
	imdbVotes: "N/A",
};